name: Deploy Hexo Blog

on:
  push:
    branches:
      - main  # 监听推送到 main 分支的操作
    paths:
      - 'source/_posts/**'  # 只在 source/_posts 下的文件变化时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库的最新版本
      - name: Checkout repository
        uses: actions/checkout@v3

      # 检查 _posts 目录是否存在
      - name: Check if _posts directory exists
        run: |
          if [ ! -d "./source/_posts" ]; then
            echo "Directory ./source/_posts does not exist. Exiting."
            exit 1
          fi

      # 使用 rsync 连接到你的服务器
      - name: Copy files to server using rsync
        run: |
          # 检查 _posts 目录是否为空
          if [ "$(ls -A ./source/_posts/)" ]; then
            echo "Syncing files..."
            sshpass -p "${{ secrets.SERVER_PASSWORD }}" rsync -avz --ignore-errors --delete --progress -e "ssh -o StrictHostKeyChecking=no" ./source/_posts/ root@${{ secrets.SERVER_HOST }}:/blog/source/_posts/
          else
            echo "No files to sync in ./source/_posts/. Copying keep.md instead."
            # 复制 keep.md 文件到服务器
            sshpass -p "${{ secrets.SERVER_PASSWORD }}" rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no" ./source/_posts/keep.md root@${{ secrets.SERVER_HOST }}:/blog/source/_posts/
          fi

      # 在服务器上执行 Hexo 相关命令
      - name: Run hexo commands on server
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /blog  # 进入服务器上的 Hexo 目录
            hexo g  # 生成静态文件
          EOF
