name: Generate SSH Key

on: [push]

jobs:
  generate-key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate SSH Key
        run: |
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
          echo "Private Key:"
          cat ~/.ssh/id_rsa
          echo "Public Key:"
          cat ~/.ssh/id_rsa.pub

      - name: Save public key to output
        id: save_key
        run: echo "::set-output name=public_key::$(cat ~/.ssh/id_rsa.pub)"
      
      - name: Display generated keys
        run: |
          echo "Here is the private key:"
          cat ~/.ssh/id_rsa
          echo "Here is the public key:"
          cat ~/.ssh/id_rsa.pub
